### ISSUE TITLE
Is HcsCreateOperation needed?

### ISSUE THREAD

**Issue by krytarowski** [Biswa96/hvtool#1]
hvtool uses `HcsCreateOperation(NULL, NULL)`.

e.g. here:

```
    hcsOperation = HcsCreateOperation(NULL, NULL);
    hRes = HcsEnumerateComputeSystems(NULL, hcsOperation);
    hRes = HcsWaitForOperationResult(hcsOperation, INFINITE, &result);
```

Is it needed? Why?

**Comment by Biswa96** [comment]
This is just a experimental project and I got the information from WSL's LxssManager.dll. I didn't dive into the haystack of HCS functions. Are you going to use it in any project?

**Comment by krytarowski** [comment]
> I got the information from WSL's LxssManager.dll

How did you get it from that DLL? Did you do disassemblation?

**Comment by Biswa96** [comment]
> How did you get it from that DLL? 

[It's complicated][1] 😈 If the discussion is temporary I can go with IRC. If the discussion is for a serious project I would like to be in a public discussion, not email.

[1]: https://reverseengineering.stackexchange.com/

**Comment by krytarowski** [comment]
Please catch me on FreeNode, channel #hvtool.

**Comment by Biswa96** [comment]
Answering to the main question: Yes, `HcsCreateOperation()` is needed. Internally, it allocates `HCS_OPERATION`, a reference counted lifetime object (a opaque structure), like a big chunk of buffer and returns it. It calls an internal function `MakeClientOperationHandle()` which is called for every VM operations.

The details is found in `computecore.dll` and may not be fully correct.

**Comment by krytarowski** [comment]
OK. The main question is answered!
